name: 早安天气推送
on:
  schedule:
    - cron: '0 0 * * *' # UTC时间0点 = 北京时间早上8点
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependency
        run: pip install requests
      - name: Run script
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          QWEATHER_KEY: ${{ secrets.QWEATHER_KEY }}
        run: python main.py
