name: 微信天气推送
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: '运行脚本'
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          AMAP_KEY: ${{ secrets.AMAP_KEY }}
        run: python main.py
